#!/data/data/com.termux/files/usr/bin/sh
# su.sh — resolve a working root shell, and run commands through it.
#
# Shared by the engine (bin/android-settings) and every hook. Sourced, never
# executed: the engine runs it in-tree / from the store, a runit-spawned hook
# runs the copy install-hook drops in ~/.local/libexec/android-settings/lib.
#
# Two shapes of "no su" have to work:
#
#   native Termux — /system/bin/su (KernelSU/Magisk) or `su` on PATH elevates;
#   the Nix chroot — the real su is hidden (/system/bin/su and /data/adb are not
#     mounted) and $PREFIX/bin/su is the Termux stub that only prints "No su
#     program found". Root there comes from KernelSU's ksud CLI: libksud.so is a
#     plain file under $HOME and `debug su -g` runs a command in the global
#     mount namespace — the same route the interactive fish su/sudo functions
#     use.
#
# The ksud route is wrapped in a generated `su -c` shim so $SU_BIN keeps its
# meaning for everything that uses it (including lib/notify.sh, which calls
# "$SU_BIN" -c ... directly).
#
# API:
#   resolve_su           -> 0 and $SU_BIN set, or 1 (nothing is printed)
#   need_root            -> resolve_su, or die loudly (engine-style)
#   as_root CMD          -> run CMD as root, retries, stdout passes through
#   as_root_out CMD      -> run CMD as root, print stdout only (poll loops)
#   as_root_detached CMD -> run CMD as root in the background (actions)
#
# CMD is a single shell command string: it is handed to the root shell verbatim,
# so a caller that interpolates data must quote it (see as_quote in hook.sh).

# Sourced from several places (engine, hooks, notify.sh) — the guard keeps the
# definitions from being re-bound and re-resolving su mid-run.
[ -n "${AS_SU_SH:-}" ] && return 0
AS_SU_SH=1

AS_STATE_BASE=${AS_STATE_BASE:-$HOME/.local/state/aliyss-android-settings}
# The root shell does NOT always get a useful PATH (seen during the home-manager
# switch: `settings: inaccessible or not found`), so pin the Android system
# dirs in front of whatever PATH it inherits. Overridable on purpose: the test
# suite points it at tests/fake so no test can reach the real /system/bin.
ANDROID_PATH=${ANDROID_PATH:-/system/bin:/system/xbin:/vendor/bin}

# Diagnostics that must work even where no hook log() exists yet.
as_warn() { printf '[android-settings] !! %s\n' "$*" >&2; }

SU_BIN=""
KSUD_LIB=${KSUD_LIB:-$HOME/sukisu-mgr/lib/arm64-v8a/libksud.so}
KSUD_LINKER=${KSUD_LINKER:-/system/bin/linker64}

# A candidate is only good if it really elevates: inside the chroot the Termux
# stub sits at the front of the search order and always fails.
su_confirmed() { # $1 = candidate binary
  _su_cand_out=$("$1" -c 'id -u' 2>/dev/null) || return 1
  # `id -u` prints "0\n"; word-splitting trims it without needing tr/sed.
  for _su_cand_w in $_su_cand_out; do
    [ "$_su_cand_w" = 0 ] && return 0
  done
  return 1
}

# Generate (once) the `su -c` shim over libksud.so and print its path.
su_write_ksud_shim() {
  _su_shim="$AS_STATE_BASE/su-ksud"
  # Regenerate when missing, when the body changed (SHIM_REV — bump it with any
  # edit below), or when it points at a different libksud (that path can move
  # with a SukiSU update). NOTE: this heredoc is unquoted, so backticks and $
  # must not appear in it — a stray pair would run a command here.
  SHIM_REV=2
  if [ ! -x "$_su_shim" ] || ! grep -q "shim-rev=$SHIM_REV" "$_su_shim" 2>/dev/null \
    || ! grep -q "$KSUD_LIB" "$_su_shim" 2>/dev/null; then
    mkdir -p "$AS_STATE_BASE" 2>/dev/null || return 1
    cat >"$_su_shim" <<EOF
#!/data/data/com.termux/files/usr/bin/sh
# Generated by android-settings — do not edit (shim-rev=$SHIM_REV).
# su -c 'cmd' over KernelSU's ksud CLI, for hosts where the real su is not
# reachable (inside the Nix chroot). Commands are read on stdin, -g selects the
# global mount namespace, and the last command's exit status is propagated.
# PATH has to hold the Android system dirs: ksud runs the command through a
# shell it resolves on PATH, so a bare activation PATH (home-manager's own bin,
# with no sh/id/pm) fails with "No such file or directory".
PATH=$ANDROID_PATH
export PATH
[ "\${1:-}" = "-c" ] && shift
printf '%s\\n' "\$*" | "$KSUD_LINKER" "$KSUD_LIB" debug su -g
EOF
    chmod 700 "$_su_shim" || return 1
  fi
  printf '%s' "$_su_shim"
}

resolve_su() {
  [ -n "$SU_BIN" ] && return 0
  for c in su /system/bin/su /system/xbin/su /sbin/su; do
    _su_cand=$(command -v "$c" 2>/dev/null) || continue
    [ -n "$_su_cand" ] || continue
    if su_confirmed "$_su_cand"; then
      SU_BIN=$_su_cand
      return 0
    fi
  done
  if [ -x "$KSUD_LINKER" ] && [ -f "$KSUD_LIB" ]; then
    SU_BIN=$(su_write_ksud_shim) && [ -n "$SU_BIN" ] && return 0
    SU_BIN=""
  fi
  return 1
}

need_root() {
  resolve_su || { as_warn "no root available (need KernelSU/Magisk su, or libksud.so)"; exit 1; }
}

# Single attempt, stdout passes through, stderr captured for the caller's
# message. `$ANDROID_PATH` is prepended because the root shell's PATH is
# whatever it inherits (often the activation's, with no settings/cmd/pm).
as_root_once() { # $1 = command
  _su_err="${AS_STATE_BASE}/su.err"
  mkdir -p "$AS_STATE_BASE" 2>/dev/null || true
  "$SU_BIN" -c "PATH=$ANDROID_PATH:\$PATH; export PATH; $1" 2>"$_su_err"
}

as_root() { # $1 = command; retries — su can lose the first race at boot
  resolve_su || return 1
  _su_i=0
  while :; do
    as_root_once "$1" && return 0
    _su_i=$((_su_i + 1))
    [ "$_su_i" -ge 3 ] && break
    sleep 1
  done
  as_warn "su failed ($(head -c 200 "${AS_STATE_BASE}/su.err" 2>/dev/null || true))"
  return 1
}

# Poll loops call this every few seconds, so it must be cheap: one su spawn, no
# retries, stderr dropped, stdout only. Failure is the caller's business.
as_root_out() { # $1 = command; prints its stdout
  resolve_su || return 1
  "$SU_BIN" -c "PATH=$ANDROID_PATH:\$PATH; export PATH; $1" 2>/dev/null
}

# Fire-and-forget for actions: a slow command must not stall the loop. The
# subshell keeps the loop's `set -e`-less scripts from waiting on it either way.
as_root_detached() { # $1 = command
  resolve_su || return 1
  "$SU_BIN" -c "PATH=$ANDROID_PATH:\$PATH; export PATH; $1" >/dev/null 2>&1 &
}
